[tool.poetry]
name = "back-finva"
version = "0.1.0"
description = ""
authors = ["Ilker Francisco Zoni Gallegos"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
uvicorn = "^0.34.0"
fastapi = "^0.115.8"
alembic = "^1.14.1"
sqlalchemy = "^2.0.37"
pydantic-settings = "^2.7.1"
asyncpg = "^0.30.0"
dependency-injector = "^4.45.0"
psycopg2 = "^2.9.10"
requests = "^2.32.3"
pydantic = {extras = ["email"], version = "^2.10.6"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
