"""inserts para las sucursales

Revision ID: 37f3eda3f914
Revises: f861c84c211c
Create Date: 2025-02-03 22:09:13.907829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37f3eda3f914'
down_revision: Union[str, None] = 'f861c84c211c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sucursales_table = sa.table(
        'sucursales',
        sa.column('nombre', sa.String),
        sa.column('calle', sa.String),
        sa.column('numero exterior', sa.Integer),
        sa.column('ciudad', sa.String),
        sa.column('estado', sa.String)
    )
    
    op.bulk_insert(
        sucursales_table,
        [
            {
                'nombre': 'KTM Ferbel Coapa',
                'calle': 'Canal de Miramontes',
                'numero exterior': 3000,
                'ciudad': 'Coyoacán',
                'estado': 'CDMX'
            },
            {
                'nombre': 'KTM Ferbel Satélite',
                'calle': 'Periférico Blvd. Manuel Ávila Camacho',
                'numero exterior': 1920,
                'ciudad': 'Naucalpan',
                'estado': 'Méx.'
            },
            {
                'nombre': 'Yamaha Ferbel Satélite',
                'calle': 'Av. Patriotismo',
                'numero exterior': 98,
                'ciudad': 'Miguel Hidalgo',
                'estado': 'CDMX'
            },
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DELETE FROM sucursales
        WHERE nombre IN ('KTM Ferbel Coapa', 'KTM Ferbel Satélite', 'Yamaha Ferbel Satélite')
        """
    )
    # ### end Alembic commands ###
