"""migracion con datos de motocicletas

Revision ID: 4294c633bd32
Revises: 5fcbad4d38cf
Create Date: 2025-02-03 16:54:21.447205

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4294c633bd32"
down_revision: Union[str, None] = "5fcbad4d38cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Definir una tabla temporal con las columnas necesarias
    motocicletas_table = sa.table(
        "motocicletas",
        sa.column("marca", sa.String),
        sa.column("modelo", sa.String),
        sa.column("anio", sa.Integer),
    )

    # Lista de 50 registros de ejemplo
    records = [
        {"marca": "KTM", "modelo": "Duke 390", "anio": 2020},
        {"marca": "KTM", "modelo": "RC 390", "anio": 2021},
        {"marca": "Yamaha", "modelo": "MT-07", "anio": 2021},
        {"marca": "Yamaha", "modelo": "R1", "anio": 2022},
        {"marca": "Honda", "modelo": "CBR500R", "anio": 2019},
        {"marca": "Suzuki", "modelo": "GSX-R750", "anio": 2020},
        {"marca": "Ducati", "modelo": "Panigale V4", "anio": 2021},
        {"marca": "BMW", "modelo": "S1000RR", "anio": 2022},
        {"marca": "Aprilia", "modelo": "Tuono V4", "anio": 2021},
        {"marca": "Kawasaki", "modelo": "Ninja 400", "anio": 2020},
        {"marca": "KTM", "modelo": "1290 Super Duke", "anio": 2022},
        {"marca": "Yamaha", "modelo": "YZF-R3", "anio": 2020},
        {"marca": "Honda", "modelo": "CBR650R", "anio": 2021},
        {"marca": "Suzuki", "modelo": "SV650", "anio": 2019},
        {"marca": "Ducati", "modelo": "Monster 821", "anio": 2020},
        {"marca": "BMW", "modelo": "F900R", "anio": 2021},
        {"marca": "Aprilia", "modelo": "RSV4", "anio": 2022},
        {"marca": "Kawasaki", "modelo": "Z900", "anio": 2021},
        {"marca": "KTM", "modelo": "890 Duke", "anio": 2020},
        {"marca": "Yamaha", "modelo": "XSR700", "anio": 2019},
        {"marca": "Honda", "modelo": "Rebel 500", "anio": 2021},
        {"marca": "Suzuki", "modelo": "V-Strom 650", "anio": 2020},
        {"marca": "Ducati", "modelo": "Diavel", "anio": 2022},
        {"marca": "BMW", "modelo": "R1250GS", "anio": 2021},
        {"marca": "Aprilia", "modelo": "Shiver 750", "anio": 2022},
        {"marca": "Kawasaki", "modelo": "Versys 650", "anio": 2021},
        {"marca": "KTM", "modelo": "Freeride", "anio": 2020},
        {"marca": "Yamaha", "modelo": "FZ-07", "anio": 2021},
        {"marca": "Honda", "modelo": "CB650R", "anio": 2022},
        {"marca": "Suzuki", "modelo": "Boulevard M109R", "anio": 2020},
        {"marca": "Ducati", "modelo": "Scrambler Icon", "anio": 2021},
        {"marca": "BMW", "modelo": "R nineT", "anio": 2022},
        {"marca": "Aprilia", "modelo": "RS 660", "anio": 2021},
        {"marca": "Kawasaki", "modelo": "Ninja ZX-6R", "anio": 2022},
        {"marca": "KTM", "modelo": "790 Duke", "anio": 2021},
        {"marca": "Yamaha", "modelo": "MT-09", "anio": 2020},
        {"marca": "Honda", "modelo": "Africa Twin", "anio": 2022},
        {"marca": "Suzuki", "modelo": "GSX-S750", "anio": 2021},
        {"marca": "Ducati", "modelo": "SuperSport", "anio": 2020},
        {"marca": "BMW", "modelo": "F850GS", "anio": 2022},
        {"marca": "Aprilia", "modelo": "Tuono 1000", "anio": 2021},
        {"marca": "Kawasaki", "modelo": "Ninja H2R", "anio": 2022},
        {"marca": "KTM", "modelo": "690 Enduro R", "anio": 2020},
        {"marca": "Yamaha", "modelo": "XSR900", "anio": 2021},
        {"marca": "Honda", "modelo": "Gold Wing", "anio": 2022},
        {"marca": "Suzuki", "modelo": "Hayabusa", "anio": 2021},
        {"marca": "Ducati", "modelo": "Multistrada V4", "anio": 2022},
        {"marca": "BMW", "modelo": "K1600", "anio": 2021},
        {"marca": "Aprilia", "modelo": "RSV4 RF", "anio": 2022},
        {"marca": "Kawasaki", "modelo": "Z H2", "anio": 2021},
    ]

    op.bulk_insert(motocicletas_table, records)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    modelos = (
        "Duke 390",
        "RC 390",
        "MT-07",
        "R1",
        "CBR500R",
        "GSX-R750",
        "Panigale V4",
        "S1000RR",
        "Tuono V4",
        "Ninja 400",
        "1290 Super Duke",
        "YZF-R3",
        "CBR650R",
        "SV650",
        "Monster 821",
        "F900R",
        "RSV4",
        "Z900",
        "890 Duke",
        "XSR700",
        "Rebel 500",
        "V-Strom 650",
        "Diavel",
        "R1250GS",
        "Shiver 750",
        "Versys 650",
        "Freeride",
        "FZ-07",
        "CB650R",
        "Boulevard M109R",
        "Scrambler Icon",
        "R nineT",
        "RS 660",
        "Ninja ZX-6R",
        "790 Duke",
        "MT-09",
        "Africa Twin",
        "GSX-S750",
        "SuperSport",
        "F850GS",
        "Tuono 1000",
        "Ninja H2R",
        "690 Enduro R",
        "XSR900",
        "Gold Wing",
        "Hayabusa",
        "Multistrada V4",
        "K1600",
        "RSV4 RF",
        "Z H2",
    )
    op.execute(sa.text(f"DELETE FROM motocicletas WHERE modelo IN {modelos}"))
    # ### end Alembic commands ###
