"""se agrega tabla de usuarios que se registren

Revision ID: b09dca6a6290
Revises: d12e087c3266
Create Date: 2025-02-04 01:12:22.637903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b09dca6a6290'
down_revision: Union[str, None] = 'd12e087c3266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=50), nullable=True),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('segundo_apellido', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('id_motocicleta', sa.Integer(), nullable=False),
    sa.Column('calle', sa.String(length=100), nullable=True),
    sa.Column('numero_interior', sa.Integer(), nullable=True),
    sa.Column('numero_exterior', sa.Integer(), nullable=True),
    sa.Column('ciudad', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_motocicleta'], ['motocicletas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_motocicletas_id'), 'motocicletas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_motocicletas_id'), table_name='motocicletas')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
