"""se agrega lat y lng para la tabla

Revision ID: d12e087c3266
Revises: 37f3eda3f914
Create Date: 2025-02-03 23:36:41.283167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd12e087c3266'
down_revision: Union[str, None] = '37f3eda3f914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sucursales', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('sucursales', sa.Column('lng', sa.Float(), nullable=True))
    op.execute("""
        UPDATE sucursales
        SET lat = 19.3025, lng = -99.1355
        WHERE nombre = 'KTM Ferbel Coapa';
        
        UPDATE sucursales
        SET lat = 19.5089, lng = -99.2399
        WHERE nombre = 'KTM Ferbel Satélite';

        UPDATE sucursales
        SET lat = 19.4057, lng = -99.1768
        WHERE nombre = 'Yamaha Ferbel Satélite';
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sucursales', 'lng')
    op.drop_column('sucursales', 'lat')
    # ### end Alembic commands ###
