"""tabla de sucursales

Revision ID: f861c84c211c
Revises: 4294c633bd32
Create Date: 2025-02-03 21:44:36.306103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f861c84c211c'
down_revision: Union[str, None] = '4294c633bd32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sucursales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('calle', sa.String(length=50), nullable=False),
    sa.Column('numero exterior', sa.Integer(), nullable=False),
    sa.Column('ciudad', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sucursales')
    # ### end Alembic commands ###
